language: node_js
node_js:
    - "4.9.1"

branches:
    only:
        - master
        - v1.x

install:
    - npm install grunt-cli
    - npm install

cache:
    directories:
        - node_modules

script:
    - ./node_modules/.bin/grunt travis
